# Generated by Django 3.2 on 2022-06-26 07:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('tariff', models.CharField(blank=True, choices=[('Нулевой', 'Нулевой'), ('Базовый', 'Базовый'), ('Премиум', 'Премиум')], default='Нулевой', max_length=50, null=True)),
                ('status', models.CharField(choices=[('в процессе', 'в процессе'), ('завершена', 'завершена'), ('свободная', 'свободная')], default='свободная', max_length=20)),
                ('services', models.CharField(blank=True, choices=[('сдать ежемесячный отчет для ОсОО', 'сдать ежемесячный отчет для ОсОО'), ('сдать ежемесячный отчет для ИП', 'сдать ежемесячный отчет для ИП'), ('сдать декларацию', 'сдать декларацию')], max_length=100, null=True)),
                ('deadline', models.DateField(default=datetime.date(2022, 7, 10))),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('клиент', 'клиент'), ('провайдер', 'провайдер')], default='клиент', max_length=30, verbose_name='Выберите свою роль')),
                ('company_form', models.CharField(choices=[('ОсОО', 'ОсОО'), ('ИП', 'ИП')], default='ОсОО', max_length=10, verbose_name='Правовая форма')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('company_inn', models.CharField(max_length=14, verbose_name='ИНН компании')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('tax_regime', models.CharField(choices=[('Общий налоговый режим', 'Общий налоговый режим'), ('Единый налог', 'Единый налог'), ('Патент', 'Патент'), ('Другое', 'Другое')], default='Общий налоговый режим', max_length=50, verbose_name='Режим налогообложения')),
                ('operation_amount', models.CharField(max_length=20, verbose_name='Количество торговых операций')),
                ('employees_quantity', models.CharField(max_length=10, verbose_name='Количество сотрудников')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_last_name', models.CharField(max_length=100, verbose_name='ФИО бухгалтера')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('INN', models.CharField(max_length=14, verbose_name='ИНН')),
                ('accountant_phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('city', models.CharField(choices=[('Бишкек', 'Бишкек'), ('Ош', 'Ош')], default='Бишкек', max_length=50, verbose_name='Выберите город')),
                ('education', models.CharField(choices=[('Высшее', 'Высшее'), ('Курсы', 'Курсы'), ('Другое', 'Другое')], default='Высшее', max_length=50, verbose_name='Образование')),
                ('experience', models.CharField(choices=[('Есть', 'Есть'), ('Нет', 'Нет')], default='Есть', max_length=20, verbose_name='Опыт работы')),
                ('payment_methods', models.CharField(choices=[('Мбанк', 'Мбанк'), ('Элсом', 'Элсом')], default='Мбанк', max_length=30, verbose_name='Способы оплаты')),
                ('upload_files', models.FileField(upload_to='accountant_docs/', verbose_name='Загрузить файлы (дипломы, сертификаты)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
