# Generated by Django 3.2 on 2022-06-27 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 7, 11)),
        ),
    ]
