# Generated by Django 3.2 on 2022-06-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_application_deadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
