# Generated by Django 3.2 on 2022-06-28 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_delete_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 7, 12)),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(default='клиент', max_length=30, verbose_name='Введите свои данные'),
        ),
    ]
