# Generated by Django 3.2 on 2022-06-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20220628_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('клиент', 'клиент')], default='клиент', max_length=30, verbose_name='Выберите свою роль'),
        ),
    ]
