# Generated by Django 3.2 on 2022-07-06 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 7, 20)),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.SmallIntegerField(verbose_name='Номер телефона'),
        ),
    ]
