# Generated by Django 3.2 on 2022-07-16 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20220706_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 7, 30)),
        ),
    ]
