# Generated by Django 3.2 on 2022-07-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_application_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='INN',
            field=models.CharField(max_length=14, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_inn',
            field=models.CharField(max_length=14, unique=True, verbose_name='ИНН компании'),
        ),
    ]
