# Generated by Django 3.2 on 2022-07-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20220716_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('в процессе', 'в процессе'), ('завершена', 'завершена'), ('новая', 'новая')], default='новая', max_length=20),
        ),
    ]
