# Generated by Django 3.2 on 2022-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('в процессе', 'в процессе'), ('завершена', 'завершена'), ('новая', 'новая')], default='завершена', max_length=20),
        ),
    ]
