# Generated by Django 3.2 on 2022-07-21 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20220716_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_type',
        ),
        migrations.AlterField(
            model_name='application',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 8, 4)),
        ),
    ]
