# Generated by Django 3.2 on 2022-07-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20220721_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='INN',
            field=models.SmallIntegerField(unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_inn',
            field=models.SmallIntegerField(unique=True, verbose_name='ИНН компании'),
        ),
    ]
