# Generated by Django 3.2 on 2022-07-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20220721_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='INN',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='accountant',
            name='accountant_phone_number',
            field=models.PositiveSmallIntegerField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_inn',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='ИНН компании'),
        ),
        migrations.AlterField(
            model_name='client',
            name='employees_quantity',
            field=models.PositiveSmallIntegerField(max_length=10, verbose_name='Количество сотрудников'),
        ),
        migrations.AlterField(
            model_name='client',
            name='operation_amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество торговых операций'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер телефона'),
        ),
    ]
